# Generated by Django 3.1.2 on 2020-10-17 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=datetime.datetime(2020, 10, 17, 9, 15, 13, 104179, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
